Repository Arctic-Thread/KurbSide, pull requests merged in 2021-04, with the labels that each got.

#179 Sales
  KurbSide/Controllers/BusinessController.cs
  KurbSide/Controllers/OrderController.cs
  KurbSide/Controllers/StoreController.cs
  KurbSide/Models/Business.cs
  KurbSide/Models/KSContext.cs
  KurbSide/Models/Metadata/ItemMetaData.cs
  KurbSide/Models/Metadata/SaleMetadata.cs
  KurbSide/Models/Sale.cs
  KurbSide/Utilities/KSOrderUtilities.cs
  KurbSide/ViewComponents/CartViewComponent.cs
  KurbSide/Views/Business/CreateSale.cshtml
  KurbSide/Views/Business/EditSale.cshtml
  KurbSide/Views/Business/Index.cshtml
  KurbSide/Views/Business/ManageSaleItem.cshtml
  KurbSide/Views/Business/SalesList.cshtml
  KurbSide/Views/Order/Checkout.cshtml
  KurbSide/Views/Shared/Components/Cart/Default.cshtml
  KurbSide/Views/Store/Catalogue.cshtml
  KurbSide/wwwroot/css/Business/BusinessSales.css
  KurbSide/wwwroot/css/Store/Catalogue.css
  KurbSide/wwwroot/js/Business/Sales/AddItemToSale.js
Labels: code

#183 Sales unit tests
  KurbSide/Views/Business/EditSale.cshtml
  KurbSide/Views/Business/SalesList.cshtml
  KurbSideTest/BaseTest.cs
  KurbSideTest/SaleTests.cs
Labels: code

#185 Reports
  KurbSide/Controllers/ReportsController.cs
  KurbSide/KurbSide.csproj
  KurbSide/Views/Reports/ViewAllCanceledOrders.cshtml
  KurbSide/Views/Reports/ViewAllCompletedOrders.cshtml
  KurbSide/Views/Reports/ViewAllItemsReport.cshtml
  KurbSide/Views/Reports/ViewAllOrdersReport.cshtml
  KurbSide/Views/Reports/ViewAllPendingOrders.cshtml
  KurbSide/Views/Reports/ViewAllReportList.cshtml
  KurbSide/Views/Reports/ViewAvailableItemsReport.cshtml
  KurbSide/Views/Reports/ViewRemovedItemsReport.cshtml
  KurbSideTest/KurbSideTest.csproj
  KurbSideTest/ReportTests.cs
Labels: code, tests

#186 Notifications
  KurbSide/Controllers/NotificationsController.cs
  KurbSide/Controllers/OrderController.cs
  KurbSide/KurbSide.csproj
  KurbSide/Models/AspNetUsers.cs
  KurbSide/Models/KSContext.cs
  KurbSide/Models/Notification.cs
  KurbSide/Service/Notifications&Emails/KSEmail.cs
  KurbSide/Service/Notifications&Emails/KSNotification.cs
  KurbSide/Service/Notifications&Emails/KSNotificationAndEmails.cs
  KurbSide/Service/Notifications&Emails/OrderStatus.cs
  KurbSide/ViewComponents/NavBarViewComponent.cs
  KurbSide/Views/Notifications/Index.cshtml
  KurbSide/Views/Shared/Components/NavBar/Default.cshtml
Labels: code

#189 Unit Test | UC31 - Business / Member Views Notifications
  KurbSide/Views/Shared/Components/NavBar/Default.cshtml
  KurbSideTest/NotificationTests.cs
Labels: tests
